# Generated by Django 5.2.5 on 2025-08-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_order_product_order_bonus_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shirtigo_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shirtigo_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
