# Generated by Django 5.2.5 on 2025-09-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_order_bonus_product_remove_order_main_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="print_position",
            field=models.CharField(
                blank=True,
                help_text="Selected print position for this order item",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="singleproduct",
            name="print_position",
            field=models.CharField(
                blank=True,
                help_text="Position to print on the product (e.g., Front, Back, Left Sleeve)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usercart",
            name="print_position",
            field=models.CharField(
                blank=True,
                help_text="Selected print position for this cart item",
                max_length=50,
                null=True,
            ),
        ),
    ]
