# Generated by Django 5.2.5 on 2025-09-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_orderitem_print_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="personalization",
            field=models.TextField(
                blank=True,
                help_text="Custom personalization text from customer",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="print_position",
            field=models.CharField(
                blank=True,
                help_text="Print position from order items",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="personalization",
            field=models.TextField(
                blank=True,
                help_text="Personalization text for this order item",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usercart",
            name="personalization",
            field=models.TextField(
                blank=True,
                help_text="Personalization text for this cart item",
                null=True,
            ),
        ),
    ]
