# Generated by Django 5.2.5 on 2025-09-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_order_personalization_order_print_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="personalization",
            field=models.TextField(
                blank=True,
                help_text="Custom personalization text from customer",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="personalization",
            field=models.TextField(
                blank=True,
                help_text="Personalization text for this order item",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usercart",
            name="personalization",
            field=models.TextField(
                blank=True,
                help_text="Personalization text for this cart item",
                max_length=256,
                null=True,
            ),
        ),
    ]
